### PR TITLE
Various mpi bugs

### LINKED ISSUE #1656: Bug in IBTK_MPI::allGather()
We do not handle the corner case of x_in being nullptr or x_in_size being zero properly. A processor may not have anything to contribute to the all gather operation. Presently the code seg faults because we do 

`mpi_type_id(x_in[0])` 

here: https://github.com/IBAMR/IBAMR/blob/master/ibtk/include/ibtk/private/IBTK_MPI-inl.h#L147

 If `x_in` is nullptr or has no memory then there is an error. Possible fix that I did locally:

```    
    T dummy_value;
    MPI_Allgatherv(x_in,
                   size_in,
                   mpi_type_id(dummy_value),
                   x_out,
                   rcounts.data(),
                   disps.data(),
                   mpi_type_id(dummy_value),
                   IBTK_MPI::getCommunicator());
```

MPI_Allgatherv seems to handle the case of x_in == nullptr and x_in_size == 0 properly. It is our mpi_type passing that causes segfault.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #1656 as well as some other minor issues.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

File: ibtk/src/utilities/IBTK_MPI.cpp [hunk 1]
```diff
@@ -43,30 +44,33 @@ IBTK_MPI::getSAMRAIWorld()
 #if SAMRAI_VERSION_MAJOR == 2
     return SAMRAI::tbox::SAMRAI_MPI::commWorld;
 #else
-    return SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld()
+    return SAMRAI::tbox::SAMRAI_MPI::getSAMRAIWorld();
```
Comment (boyceg) [inline ibtk/src/utilities/IBTK_MPI.cpp:47]: Does this mean you are messing around with SAMRAI 3/4??? 😀

**Review by boyceg — APPROVED** [review]

File: ibtk/src/utilities/IBTK_MPI.cpp (hunk 1 above)
Comment (drwells) [reply ibtk/src/utilities/IBTK_MPI.cpp:47]: No, not yet; it's just that what we have clearly won't work without the `;`.
