### PR TITLE
Bug fixes to compute time steps in parallel.

### LINKED ISSUE #1022: Different processors use different time steps
https://github.com/IBAMR/IBAMR/blob/59afafa326986b0f27e5e957b8c09e87a8ef3a69/ibtk/src/utilities/HierarchyIntegrator.cpp#L330-L350

@boyceg Is there a reason why we don't do a `minReduction` when we compute time step sizes? I'm getting patches that run at different timesteps depending on how the patches are laid out on processors.

### PR DESCRIPTION
**Pull request by abarret**
### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [ ] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

Fixes #1022. `AdvDiffHierarchyIntegrator` did not compute timestep sizes consistent across all processors. I've updated the documentation in `HierarchyIntegrator` to note that time step sizes should be consistent in implementations of `getMinimumTimeStepSizeSpecialized` and `getMaximumTimeStepSizeSpecialized`. ~~This is also fixes a minor bug in `HierarchyIntegrator` to select the smallest of all timesteps in computing the minimum timestep.~~

### CODE REVIEW

File: ibtk/include/ibtk/HierarchyIntegrator.h [hunk 1]
```diff
@@ -699,7 +699,8 @@ class HierarchyIntegrator : public SAMRAI::mesh::StandardTagAndInitStrategy<NDIM
 
     /*!
      * Virtual method to compute an implementation-specific minimum stable time
-     * step size.
+     * step size. Implementations should ensure that the returned time step is
+     * consistent across all processors.
```
Comment (boyceg) [inline ibtk/include/ibtk/HierarchyIntegrator.h:703]: 👍

File: ibtk/include/ibtk/HierarchyIntegrator.h [hunk 2]
```diff
@@ -709,7 +710,8 @@ class HierarchyIntegrator : public SAMRAI::mesh::StandardTagAndInitStrategy<NDIM
 
     /*!
      * Virtual method to compute an implementation-specific maximum stable time
-     * step size.
+     * step size. Implementations should ensure that the returned time step is
+     * consistent across all processors.
```
Comment (boyceg) [inline ibtk/include/ibtk/HierarchyIntegrator.h:714]: 👍

File: ibtk/src/utilities/HierarchyIntegrator.cpp [hunk 3]
```diff
@@ -333,7 +333,7 @@ HierarchyIntegrator::getMinimumTimeStepSize()
     double dt = getMinimumTimeStepSizeSpecialized();
     for (const auto& child_integrator : d_child_integrators)
     {
-        dt = std::max(dt, child_integrator->getMinimumTimeStepSize());
+        dt = std::min(dt, child_integrator->getMinimumTimeStepSize());
```
Comment (boyceg) [inline ibtk/src/utilities/HierarchyIntegrator.cpp:336]: this should be `std::max()` not `std::min()`

File: src/adv_diff/AdvDiffHierarchyIntegrator.cpp [hunk 4]
```diff
@@ -978,7 +978,7 @@ AdvDiffHierarchyIntegrator::getMaximumTimeStepSizeSpecialized()
             }
         }
     }
-    return dt;
+    return SAMRAI_MPI::minReduction(dt);
```
Comment (boyceg) [inline src/adv_diff/AdvDiffHierarchyIntegrator.cpp:981]: 👍

File: ibtk/src/utilities/HierarchyIntegrator.cpp (hunk 3 above)
Comment (boyceg) [reply ibtk/src/utilities/HierarchyIntegrator.cpp:336]: The minimum time step size will be the max over all of the minimums.

The maximum time step size will be the min over all of the maximums.

Comment (abarret) [reply ibtk/src/utilities/HierarchyIntegrator.cpp:336]: Yes, I see. This isn't choosing smallest stable time steps, it's choosing minimum timesteps.

Comment (abarret) [reply ibtk/src/utilities/HierarchyIntegrator.cpp]: I'm pretty sure this is the second time I've gotten confused on this :laughing:
