### PR TITLE
Fix FEMapping with QNODAL.

### LINKED ISSUE #1209: Failed assertion when using QNODAL for PK1 stress
for the lumped + nodal scheme, I tried using `QNODAL` for the PK1 stress functions (e.g. `PK1_QUAD_TYPE="QNODAL"`). But I get a failed assertion saying 
```
P=00051:Program abort called in file ``../../../IBAMR/ibtk/lib/../src/lagrangian/FEMapping.cpp'' at line 87
P=00051:ERROR MESSAGE: 
P=00051:Failed assertion: d_reference_q_points.size() == physical_q_points.size()
```
Am I missing anything in doing this?

### PR DESCRIPTION
**Pull request by drwells**
We need to specify the element used for both the quadrature rule (since QNODAL depends on that) and also the mapping itself (which libMesh assumes is always a Lagrange-type mapping based on the nodes of the mesh).

Fixes #1209.

### IBAMR Pull Request Checklist
- [x] Does the test suite pass?
- [x] Was clang-format run?
- [x] Were relevant issues cited? Please remember to add `Fixes #12345` to close
      the issue automatically if we are fixing the problem.
- [x] Is this a change others will want to know about? If so, then has a
      changelog entry been added?
- [x] If new data structures have been added to a class then have they been set
      up appropriately for restarts? If so, ensure that the restart version
      number is incremented.
- [x] Does this change include a bug fix or new functionality? If so, a new test
      or tests should be added. New tests should run quickly (less than a minute
      in release mode). If possible, an older test should gain a new option so
      that we do not need to compile more test executables.
- [x] Did you (if your account has permission to do so) set relevant labels on
      GitHub for the pull request?

### CODE REVIEW

File: ibtk/include/ibtk/FEMapping.h [hunk 1]
```diff
@@ -220,8 +220,19 @@ class FENodalMapping : public FEMapping<dim, spacedim>
 
     /*!
      * Constructor.
+     *
+     * @param[in] quad_key The quadrature key (i.e., a complete description of
+     * the quadrature rule).
+     * @param[in] mapping_element_type The element type used to compute the
+     * mapping from the reference element to the physical element. This may be
+     * different from the element type in the quadrature rule - for example,
+     * one could provide TRI6 in the quadrature rule ant TRI3 here.
```
Comment (boyceg) [inline ibtk/include/ibtk/FEMapping.h:229]:
```suggestion
     * one could provide TRI6 in the quadrature rule and TRI3 here.
```

File: ibtk/include/ibtk/FEMapping.h [hunk 2]
```diff
@@ -344,10 +355,21 @@ class FELagrangeMapping : public FENodalMapping<dim, spacedim, n_nodes>
...
      * Constructor.
-     */
-    FELagrangeMapping(const key_type quad_key, const FEUpdateFlags update_flags);
+     *
+     * @param[in] quad_key The quadrature key (i.e., a complete description of
+     * the quadrature rule).
+     * @param[in] mapping_element_type The element type used to compute the
+     * mapping from the reference element to the physical element. This may be
+     * different from the element type in the quadrature rule - for example,
+     * one could provide TRI6 in the quadrature rule ant TRI3 here.
```
Comment (boyceg) [inline ibtk/include/ibtk/FEMapping.h:366]:
```suggestion
     * one could provide TRI6 in the quadrature rule and TRI3 here.
```

**Review by boyceg — APPROVED** [review]
