### PR TITLE
Run IWYU and fix the resulting problems.

### LINKED ISSUE #807: Post 0.6: run IWYU
We should run this early in the release cycle so that we can shake out any overly zealous header deletions.

### PR DESCRIPTION
**Pull request by drwells**
Fixes #807.

IWYU made a lot of mistakes, particularly with Eigen and Boost headers. It is probably worthwhile to run this tool every couple of years but it took hours to get everything working again - its just not worthwhile to run this for every release.

### CODE REVIEW

**Comment by boyceg** [comment]
Uhhh, you want me to review this? :-D

**Comment by drwells** [comment]
I don't know. I read through the changes and deleted all the `private/` headers and other weird stuff IWYU did - it should be fine.

File: src/wave_generation/IrregularWaveGenerator.cpp [hunk 1]
```diff
@@ -15,11 +15,14 @@
 
 #include "ibamr/IrregularWaveGenerator.h"
 #include "ibamr/RNG.h"
-#include "ibamr/app_namespaces.h"
```
Comment (drwells) [inline src/wave_generation/IrregularWaveGenerator.cpp]: A major problem with IWYU pragmas is that its really hard to remember to put them everywhere we need them.
